services:
  ems_postgres:
    image: postgres
    restart: always
    ports:
      - 3333:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
  ems:
    build:
      context: ../
      dockerfile: ./EntityManagerService/Dockerfile
    ports:
      - 8200:8200
    volumes:
      - ems_logs:/digidojo/logs
    env_file:
      - .env
    depends_on:
      - ems_postgres

volumes:
  postgres:
  ems_logs: